[versions]
appcompat = "1.6.1"
material = "1.9.0"
constraintlayout = "2.1.4"
room = "2.6.1"
recyclerview = "1.3.0"
location = "21.0.1"
retrofit = "2.9.0"
gson = "2.9.0"
agp = "8.9.2"

[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }

room.runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room.compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }

location = { module = "com.google.android.gms:play-services-location", version.ref = "location" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
gson.converter = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
